"""Generate the static portfolio pages in dist/. Run with python3 build.py."""

from pathlib import Path

OUT = Path(__file__).parent / "dist"
OUT.mkdir(exist_ok=True)

NAV = [
    ("Home", "index.html", "home"),
    ("Projects", "projects.html", "projects"),
    ("Certifications", "certifications.html", "certifications"),
    ("About", "about.html", "about"),
]


def icon(name: str, size: int = 20) -> str:
    icons = {
        "sun": '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.42 1.42m11.3 11.3 1.42 1.42M2 12h2m16 0h2M4.93 19.07l1.42-1.42m11.3-11.3 1.42-1.42"/>',
        "moon": '<path d="M20.2 15.8A8.5 8.5 0 0 1 8.2 3.8 8.5 8.5 0 1 0 20.2 15.8Z"/>',
        "mail": '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>',
        "github": '<path d="M9 19c-4 1-4-2-6-2m12 4v-3.1a2.7 2.7 0 0 0-.7-2.1c2.4-.3 4.9-1.2 4.9-5.4a4.2 4.2 0 0 0-1.1-2.9 3.9 3.9 0 0 0-.1-2.9s-.9-.3-3 1.1a10.5 10.5 0 0 0-5.5 0C7.4 4.3 6.5 4.6 6.5 4.6a3.9 3.9 0 0 0-.1 2.9 4.2 4.2 0 0 0-1.1 2.9c0 4.2 2.5 5.1 4.9 5.4a2.7 2.7 0 0 0-.7 2.1V21"/>',
        "code": '<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-2-16-4 20"/>',
        "layers": '<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>',
        "phone": '<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M11 18h2"/>',
        "spark": '<path d="m12 2 1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8L12 2Zm7 15 .7 2.3L22 20l-2.3.7L19 23l-.7-2.3L16 20l2.3-.7L19 17Z"/>',
        "award": '<circle cx="12" cy="8" r="5"/><path d="m9 13-2 9 5-3 5 3-2-9"/>',
        "location": '<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
        "external": '<path d="M13 5h6v6m0-6-9 9"/><path d="M19 13v5a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5"/>',
    }
    return f'<svg width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{icons[name]}</svg>'


def nav(active: str) -> str:
    links = "".join(
        f'<a href="{href}"{(" aria-current=\"page\"" if key == active else "")}>{label}</a>'
        for label, href, key in NAV
    )
    return f'''<header class="site-header"><div class="wrap header-inner">
      <a class="brand" href="index.html" aria-label="Janith Dasanayaka, home"><span class="brand-mark">jd<span>.</span></span><span class="brand-text">JANITH DASANAYAKA</span></a>
      <nav class="site-nav" id="site-nav" aria-label="Main navigation">{links}<a class="nav-contact" href="index.html#contact">Contact</a></nav>
      <div class="header-actions"><button class="theme-toggle" type="button" aria-label="Switch theme" title="Switch theme"><span class="theme-sun">{icon("sun")}</span><span class="theme-moon">{icon("moon")}</span></button><button class="menu-toggle" type="button" aria-label="Open menu" aria-controls="site-nav" aria-expanded="false"><span></span><span></span></button></div>
    </div></header>'''


def footer() -> str:
    return f'''<footer class="site-footer"><div class="wrap footer-grid"><div><a class="brand-mark" href="index.html" aria-label="Back to home">jd<span>.</span></a><p>Software engineering, thoughtful interfaces, and practical problem solving.</p></div><div class="footer-links"><a href="projects.html">Projects</a><a href="certifications.html">Certifications</a><a href="about.html">About</a></div><div class="footer-links"><a href="mailto:djanith11@gmail.com">Email</a><a href="https://github.com/janithcd" target="_blank" rel="noopener noreferrer">GitHub</a><a href="https://www.credly.com/badges/27d896a6-e726-403c-9cfd-5f83d43ebd64/public_url" target="_blank" rel="noopener noreferrer">Credly</a></div></div><div class="wrap footer-bottom"><span>© <span data-year>2026</span> Janith Dasanayaka</span><span>Built in Colombo, Sri Lanka</span></div></footer>'''


def page(title: str, description: str, active: str, body: str) -> str:
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#0b1020"><meta name="description" content="{description}">
<title>{title} | Janith Dasanayaka</title>
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='13' fill='%230b1020'/%3E%3Ctext x='10' y='44' font-family='Arial,sans-serif' font-size='34' font-weight='700' fill='%23c4f27c'%3EJD%3C/text%3E%3C/svg%3E">
<script>try{{const p=localStorage.getItem('portfolio-theme');document.documentElement.dataset.theme=p||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark')}}catch{{document.documentElement.dataset.theme='dark'}}</script>
<link rel="stylesheet" href="styles.css"><script src="script.js" defer></script></head><body>
<a class="skip-link" href="#main">Skip to content</a><div class="scroll-progress" aria-hidden="true"></div>{nav(active)}<main id="main">{body}</main>{footer()}</body></html>'''


def tech(name: str, slug: str) -> str:
    return f'<span class="tech"><img src="assets/icons/{slug}.svg" alt="" loading="lazy" width="28" height="28"><span>{name}</span></span>'


home = f'''<section class="hero wrap"><div class="hero-copy">
  <p class="eyebrow animate-intro"><span class="status-pulse"></span> Software Engineering undergraduate · Colombo, Sri Lanka</p>
  <h1 class="animate-intro">I build software<br>that makes <em>things work.</em></h1>
  <p class="hero-lead animate-intro">I’m Janith Dasanayaka. I work across web, backend and Android development, turning real workflows into useful applications.</p>
  <div class="hero-actions animate-intro"><a class="button button-primary" href="projects.html">Explore projects</a><a class="button button-outline" href="index.html#contact">Get in touch</a></div>
  <div class="hero-facts animate-intro"><span>{icon('location',17)} Colombo, Sri Lanka</span><span>Open to software engineering internships</span></div>
  </div><div class="hero-visual animate-intro" aria-label="Current focus and featured projects"><div class="visual-head"><span class="visual-kicker">CURRENT FOCUS</span><span class="live-indicator">2026</span></div><div class="visual-title">Building across<br><em>the stack.</em></div><div class="visual-layers"><div><span class="layer-icon">{icon('code')}</span><div><strong>Web & backend</strong><small>Java · Spring Boot · React · Node.js</small></div><span class="layer-index">01</span></div><div><span class="layer-icon">{icon('phone')}</span><div><strong>Android experiences</strong><small>Device features · Firebase · Payments</small></div><span class="layer-index">02</span></div><div><span class="layer-icon">{icon('spark')}</span><div><strong>Computer vision</strong><small>Python · OpenCV · MediaPipe</small></div><span class="layer-index">03</span></div></div><div class="visual-foot"><span>Curiosity → prototype → working product</span><span class="visual-cursor" aria-hidden="true">_</span></div></div></section>
<section class="quick-strip"><div class="wrap strip-inner"><span>SOFTWARE DEVELOPMENT</span><span>FULL-STACK APPLICATIONS</span><span>OPEN SOURCE</span><span>CONTINUOUS LEARNING</span></div></section>
<section class="section wrap" id="featured"><div class="section-top reveal"><div><p class="eyebrow">01 / SELECTED WORK</p><h2>What I’ve <em>built.</em></h2></div><a class="subtle-link" href="projects.html">View all projects</a></div>
 <div class="featured-grid">
 <a class="feature-card reveal" href="projects.html#dream-ceylon"><div class="card-icon">{icon('layers',27)}</div><div class="feature-meta"><span>01 / FULL-STACK</span><span>MERN</span></div><h3>Dream Ceylon CRM</h3><p>Destination management, itineraries, quotations and branded documents for a tourism business.</p><div class="feature-bottom"><span>React · Express · MongoDB</span></div></a>
 <a class="feature-card reveal" href="projects.html#gym-system"><div class="card-icon">{icon('code',27)}</div><div class="feature-meta"><span>02 / BACKEND</span><span>JAVA</span></div><h3>Gym Management System</h3><p>Member, payment and attendance workflows in an admin-focused web application.</p><div class="feature-bottom"><span>Spring Boot · MySQL</span></div></a>
 <a class="feature-card reveal" href="projects.html#smart-tourism"><div class="card-icon">{icon('phone',27)}</div><div class="feature-meta"><span>03 / MOBILE</span><span>ANDROID</span></div><h3>Smart Tourism</h3><p>Discovery and booking experiences with cloud data, receipts and mobile device capabilities.</p><div class="feature-bottom"><span>Android · Firebase</span></div></a>
 </div></section>
<section class="toolbelt-shell"><div class="section wrap"><div class="section-top reveal"><div><p class="eyebrow">02 / TOOLKIT</p><h2>Tools I work <em>with.</em></h2></div><p class="section-note">A practical mix of languages, frameworks, data tools and development workflows.</p></div><div class="tech-grid reveal">{''.join(tech(*item) for item in [('Java','java'),('Spring Boot','spring'),('JavaScript','javascript'),('React','react'),('Node.js','nodejs'),('Python','python'),('MongoDB','mongodb'),('MySQL','mysql'),('Git','git'),('Firebase','firebase'),('Android','android'),('OpenCV','opencv')])}</div><a class="subtle-link toolkit-link" href="about.html">More about my skills</a></div></section>
<section class="section wrap"><div class="two-column-callout"><div class="reveal"><p class="eyebrow">03 / OPEN SOURCE</p><h2>Better code through<br><em>collaboration.</em></h2><p>Contributing to existing projects has taught me to understand unfamiliar code, write focused changes, run tests and respond to feedback.</p><a class="subtle-link" href="about.html#open-source">Explore contributions</a></div><div class="contribution-list reveal"><div><span>01</span><strong>Stacktale</strong><small>Java · IntelliJ plugin</small></div><div><span>02</span><strong>OpenMed</strong><small>Python · documentation</small></div><div><span>03</span><strong>URL Frontier</strong><small>Developer documentation</small></div></div></div></section>
<section class="cert-preview"><div class="wrap cert-preview-inner"><div class="reveal"><p class="eyebrow">04 / CONTINUOUS LEARNING</p><h2>Learning that goes<br><em>beyond the classroom.</em></h2><p>My AWS Certified AI Practitioner credential reflects a foundation in AI concepts and responsible use of AI on AWS.</p><a class="button button-primary" href="certifications.html">Explore certifications</a></div><div class="mini-credential reveal"><div class="credential-orbit">{icon('award',45)}</div><span>VERIFIED CREDENTIAL</span><strong>AWS Certified<br>AI Practitioner</strong><small>Issued September 2026 · Valid through September 2029</small></div></div></section>
<section class="contact-section wrap" id="contact"><div class="contact-inner reveal"><p class="eyebrow">05 / LET’S TALK</p><h2>Have a project or<br>opportunity in mind?</h2><p>I’m interested in software engineering internships, junior developer roles and projects where I can keep learning while contributing.</p><div class="contact-actions"><a class="button button-primary" href="mailto:djanith11@gmail.com?subject=Software%20Engineering%20Opportunity">{icon('mail',18)} Email Janith</a><button class="copy-email" type="button">Copy email address</button></div><a class="contact-address" href="mailto:djanith11@gmail.com">djanith11@gmail.com</a><span class="copy-status" role="status" aria-live="polite"></span></div></section>'''


def project(slug: str, number: str, kind: str, title: str, summary: str, challenge: str, build: str, focus: str, tags: list[str], repo: str, category: str, symbol: str) -> str:
    chips = "".join(f"<span>{t}</span>" for t in tags)
    return f'''<article class="case-card reveal" id="{slug}" data-category="{category}"><div class="case-top"><span>{number} / {kind}</span><span class="case-symbol">{icon(symbol,25)}</span></div><h2>{title}</h2><p class="case-summary">{summary}</p><div class="case-columns"><div><h3>The need</h3><p>{challenge}</p></div><div><h3>What I built</h3><p>{build}</p></div></div><p class="case-focus"><strong>What I learned:</strong> {focus}</p><div class="case-bottom"><div class="tags">{chips}</div><a class="subtle-link" href="{repo}" target="_blank" rel="noopener noreferrer">View repository</a></div></article>'''


projects = f'''<section class="page-hero wrap"><p class="eyebrow animate-intro">PROJECTS / PRACTICAL SOFTWARE</p><h1 class="animate-intro">Ideas into <em>working systems.</em></h1><p class="page-lead animate-intro">A selection of applications built through coursework, independent projects and real business workflows. Each one gave me a different problem to solve.</p></section>
<section class="section wrap projects-section"><div class="filter-head reveal"><div><span class="eyebrow">EXPLORE THE WORK</span><p id="project-count" aria-live="polite">Showing 4 projects</p></div><div class="filters" role="group" aria-label="Filter projects"><button type="button" class="active" data-filter="all" aria-pressed="true">All <span>4</span></button><button type="button" data-filter="web" aria-pressed="false">Web & backend <span>2</span></button><button type="button" data-filter="mobile" aria-pressed="false">Mobile <span>1</span></button><button type="button" data-filter="research" aria-pressed="false">R&D <span>1</span></button></div></div><div class="case-list">
{project('dream-ceylon','01','FULL-STACK WEB','Dream Ceylon CRM','A CRM for an inbound tourism business, designed around the day-to-day work of planning tours and preparing client documents.','Destinations, itineraries, quotations and customer communication were spread across separate tools.','A MERN application with JWT-based admin authentication, destination management, itinerary tools, dashboard reporting and branded quotation, invoice and receipt PDFs. It also includes AI-assisted itinerary and reply features.','Bringing an end-to-end business workflow into one interface, from data entry to client-ready documents.',['React','Node.js','Express','MongoDB','JWT'], 'https://github.com/janithcd/dream-ceylon-crm-mern','web','layers')}
{project('gym-system','02','JAVA BACKEND','Gym Management System','An admin-focused system for handling members, attendance, payments and access records.','Staff need reliable records and clear visibility into payments and member activity.','A Spring Boot and Thymeleaf application backed by MySQL, with authentication, validation, reports, PDF receipts, dashboard charts and administrative profiles.','Structuring backend logic and relational data around everyday operations.',['Java','Spring Boot','Thymeleaf','MySQL','JPA'], 'https://github.com/janithcd/gym-admin-system','web','code')}
{project('smart-tourism','03','ANDROID APPLICATION','Smart Tourism','A mobile tourism experience combining discovery, bookings, receipts and device features.','A tourism app needs to connect useful location-based information with a smooth booking flow.','Customer and admin workflows with Firebase data, PDF booking receipts, biometric verification, compass and location features, plus Stripe sandbox payments.','Connecting mobile device capabilities, cloud data and in-app payment flows.',['Android','Firebase','Stripe sandbox','Location'], 'https://github.com/janithcd/smart-tourism-hdp2','mobile','phone')}
{project('face-attendance','04','COMPUTER VISION','Smart Face Attendance','A prototype for real-time face recognition and liveness detection through a camera.','A face-based attendance flow needs stronger checks than a still image.','Python, OpenCV and MediaPipe process live input and use blink, head-turn and return-to-center checks based on facial landmarks.','Working with real-time camera data and software-to-hardware interactions.',['Python','OpenCV','MediaPipe','Computer vision'], 'https://github.com/janithcd/smart-face-attendance','research','spark')}
</div></section><section class="closing-banner wrap reveal"><div><p class="eyebrow">NEXT CONVERSATION</p><h2>Let’s build something useful.</h2></div><a class="button button-primary" href="mailto:djanith11@gmail.com?subject=Portfolio%20Project%20Inquiry">Get in touch</a></section>'''


certifications = f'''<section class="page-hero wrap"><p class="eyebrow animate-intro">CERTIFICATIONS / LEARNING</p><h1 class="animate-intro">Credentials backed<br>by <em>curiosity.</em></h1><p class="page-lead animate-intro">Formal learning helps me strengthen the foundations behind the projects I build. Here are my current certification and academic qualifications.</p></section>
<section class="section wrap credentials-section"><div class="section-top reveal"><div><p class="eyebrow">01 / PROFESSIONAL CERTIFICATION</p><h2>Verified <em>credential.</em></h2></div></div><article class="cert-hero reveal"><div class="cert-art"><div class="cert-art-ring"><img src="assets/icons/aws.svg" alt="AWS" width="130" height="80"></div><span>FOUNDATIONAL · AI & MACHINE LEARNING</span></div><div class="cert-body"><div class="cert-status">{icon('award',18)} Verified on Credly</div><h3>AWS Certified<br>AI Practitioner</h3><p>Foundational knowledge of AI and machine learning concepts, generative AI, responsible AI practices and AWS AI services.</p><dl class="cert-facts"><div><dt>Issued</dt><dd>28 September 2026</dd></div><div><dt>Expires</dt><dd>28 September 2029</dd></div><div><dt>Issuer</dt><dd>Amazon Web Services</dd></div></dl><a class="button button-primary" href="https://www.credly.com/badges/27d896a6-e726-403c-9cfd-5f83d43ebd64/public_url" target="_blank" rel="noopener noreferrer">Verify credential</a></div></article></section>
<section class="toolbelt-shell"><div class="section wrap"><div class="section-top reveal"><div><p class="eyebrow">02 / ACADEMIC QUALIFICATIONS</p><h2>Grounded in <em>engineering.</em></h2></div><p class="section-note">Qualifications are listed separately from professional certifications.</p></div><div class="qualification-list reveal"><article><span class="qual-year">2026 · ONGOING</span><div><h3>BSc (Hons) Software Engineering</h3><p>Birmingham City University · Expected completion in 2026</p></div><span class="qual-symbol">{icon('code')}</span></article><article><span class="qual-year">ISSUED AUG 2026</span><div><h3>Level 5 Professional Higher Diploma in Software Engineering</h3><p>Skills & Education Group Awards / UK Awards</p></div><span class="qual-symbol">{icon('award')}</span></article><article><span class="qual-year">ISSUED OCT 2025</span><div><h3>Level 4 Professional Diploma in Software Engineering</h3><p>Skills & Education Group Awards / UK Awards</p></div><span class="qual-symbol">{icon('award')}</span></article></div></div></section>
<section class="section wrap learning-note reveal"><span class="note-icon">{icon('spark',30)}</span><div><p class="eyebrow">KEEP LEARNING</p><h2>What comes next?</h2><p>I’m continuing to build my cloud foundations while improving my Java, Spring Boot, JavaScript and full-stack development skills through projects and practice.</p></div><a class="subtle-link" href="projects.html">See the projects</a></section>'''


about = f'''<section class="page-hero wrap"><p class="eyebrow animate-intro">ABOUT / THE PERSON BEHIND THE CODE</p><h1 class="animate-intro">Always learning.<br><em>Always building.</em></h1><p class="page-lead animate-intro">I’m Janith, a Software Engineering undergraduate in Colombo. I’m drawn to the point where a real problem meets a clear, dependable piece of software.</p></section>
<section class="section wrap about-layout"><div class="about-main reveal"><p class="eyebrow">01 / MY APPROACH</p><h2>From understanding<br>to implementation.</h2><p>I like to start by understanding the people and process behind a feature. Then I work through the data, API and interface until the whole journey makes sense.</p><p>My projects have taken me from full-stack business systems and Java backend work to Android development and computer vision. Each one has strengthened a different part of my engineering practice.</p><p>I’m looking for an internship where I can contribute to a real team, learn from feedback and keep improving how I build software.</p><div class="about-note"><strong>Currently exploring</strong><span>Software-to-hardware integration, automation, computer vision and cloud foundations.</span></div></div><div class="about-side reveal"><div class="side-panel"><span class="eyebrow">AT A GLANCE</span><div><span>Location</span><strong>Colombo, Sri Lanka</strong></div><div><span>Education</span><strong>BSc (Hons) Software Engineering</strong></div><div><span>Focus</span><strong>Full-stack & backend development</strong></div><div><span>Next step</span><strong>Software engineering internship</strong></div></div></div></section>
<section class="toolbelt-shell"><div class="section wrap"><div class="section-top reveal"><div><p class="eyebrow">02 / TECHNICAL TOOLKIT</p><h2>The stack I’m <em>growing.</em></h2></div><p class="section-note">Tools I’ve used in coursework, personal projects and open-source contributions.</p></div><div class="skill-categories reveal"><div><h3>Languages & frontend</h3><div class="tech-grid compact">{''.join(tech(*item) for item in [('Java','java'),('Python','python'),('JavaScript','javascript'),('HTML','html5'),('CSS','css3'),('React','react')])}</div></div><div><h3>Backend & data</h3><div class="tech-grid compact">{''.join(tech(*item) for item in [('Spring Boot','spring'),('Node.js','nodejs'),('MongoDB','mongodb'),('MySQL','mysql')])}</div></div><div><h3>Platforms & tools</h3><div class="tech-grid compact">{''.join(tech(*item) for item in [('Android','android'),('Firebase','firebase'),('AWS','aws'),('Git','git'),('OpenCV','opencv')])}</div></div></div><p class="skills-footnote">Also working with REST APIs, JPA / Hibernate, Thymeleaf, Express, Postman, Maven, Gradle and testing workflows.</p></div></section>
<section class="section wrap" id="open-source"><div class="section-top reveal"><div><p class="eyebrow">03 / OPEN SOURCE</p><h2>Learning in <em>public.</em></h2></div><p class="section-note">Small, focused contributions to projects maintained by others.</p></div><div class="open-source-grid"><article class="open-card reveal"><span>JAVA · INTELLIJ</span><h3>Stacktale</h3><p>Worked on parser edge cases and navigation behavior with Java, Gradle and automated tests.</p><a class="subtle-link" href="https://github.com/stacktale/stacktale-intellij/pull/10" target="_blank" rel="noopener noreferrer">View a pull request</a></article><article class="open-card reveal"><span>PYTHON · DOCUMENTATION</span><h3>OpenMed</h3><p>Contributed issue forms, documentation and language-support configuration through pull request workflows.</p><a class="subtle-link" href="https://github.com/janithcd/openmed" target="_blank" rel="noopener noreferrer">View repository</a></article><article class="open-card reveal"><span>DEVELOPER DOCUMENTATION</span><h3>URL Frontier</h3><p>Improved documentation on setup, concepts and API usage for new contributors and developers.</p><a class="subtle-link" href="https://github.com/janithcd/url-frontier" target="_blank" rel="noopener noreferrer">View repository</a></article></div></section>
<section class="closing-banner wrap reveal"><div><p class="eyebrow">LET’S CONNECT</p><h2>Open to the next challenge.</h2></div><a class="button button-primary" href="mailto:djanith11@gmail.com?subject=Software%20Engineering%20Opportunity">Email Janith</a></section>'''


pages = {
    "index.html": page("Software Engineer & Full-Stack Developer", "Janith Dasanayaka is a Software Engineering undergraduate in Colombo building full-stack, backend and Android applications.", "home", home),
    "projects.html": page("Projects", "Explore Janith Dasanayaka’s full-stack, Java, Android and computer vision projects.", "projects", projects),
    "certifications.html": page("Certifications & Qualifications", "AWS Certified AI Practitioner and software engineering qualifications earned by Janith Dasanayaka.", "certifications", certifications),
    "about.html": page("About", "Learn about Janith Dasanayaka’s software engineering experience, technical toolkit and open-source contributions.", "about", about),
}
for filename, content in pages.items():
    (OUT / filename).write_text(content + "\n", encoding="utf-8")
print("Generated:", ", ".join(pages))
